spring:
  application:
    name: CoreBankingApplication
  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: banking
    password: banking
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
server:
  port: 8080
